---
- hosts: localhost
  gather_facts: no
  tasks:
    - name: Create a file
      file: 
        path: /tmp/file1
        state: touch
      register: output
    - debug: msg="This is a vaule of register variable {{ output }}"
    - name: Edit a File
      lineinfile:
              path: /tmp/file1
              line: "{{ output.uid}}"
